#pragma once

enum Compiler_Events : size_t {
    CE_UNDEFINED = 0,

    CE_IMPORT_MODULE,

    CE_MODULE_RUN_LEXER,
    CE_MODULE_RUN_PARSER,

    CE_MODULE_RESOLVE_IMPORTS,
    CE_MODULE_RESOLVE_SYMBOLS,
    CE_MODULE_PROPAGATE_CONSTANTS,
    CE_MODULE_INFER_TYPES,
    CE_MODULE_RESOLVE_IFS,

    CE_MODULE_CHECK_TYPES,
    CE_MODULE_CHECK_DEPENDENCIES,

    CE_MODULE_READY,

    CE_COMPILER_ERROR,
};
