#pragma once

enum Compiler_Events : size_t {
    CE_UNDEFINED = 0,

    CE_COMPILER_START,

    CE_IMPORT_MODULE,

    CE_MODULE_RUN_LEXER,
    CE_MODULE_RUN_PARSER,

    CE_MODULE_RESOLVE_LOCAL_SYMBOLS,
    CE_MODULE_RESOLVE_IMPORTS,
    CE_MODULE_RESOLVE_EXTERNAL_SYMBOLS,
    CE_MODULE_RESOLVE_IFS,

    CE_MODULE_CHECK_DEPENDENCIES,

    CE_MODULE_READY,

    CE_COMPILER_ERROR,
    CE_COMPILER_STOP,
};
